services:
  redis:
    image: redis:7-alpine
    container_name: zoom_redis
    command: ["redis-server", "--appendonly", "yes", "--maxmemory", "28mb", "--maxmemory-policy", "noeviction"]
    mem_limit: 32m
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - internal

  core:
    build: ./core
    container_name: zoom_core
    depends_on:
      - redis
    env_file: .env
    environment:
      - TZ=Europe/Kyiv
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONUNBUFFERED=1
    mem_limit: 1024m
    memswap_limit: 1024m
    shm_size: "512m"
    restart: "no"
    volumes:
      - ./config.json:/app/config.json:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - internal

  controller:
    build: ./controller
    container_name: zoom_controller
    depends_on:
      - redis
    env_file: .env
    environment:
      - TZ=Europe/Kyiv
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CORE_CONTAINER_NAME=zoom_core
      - PYTHONUNBUFFERED=1
    mem_limit: 150m
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config.json:/app/config.json:ro
    networks:
      - internal

volumes:
  redis_data:

networks:
  internal:
    driver: bridge